// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MulttenantSaas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260126140434_AddPushSubscriptions")]
    partial class AddPushSubscriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShiftDrop.Domain.Casual", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Auth0Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InviteExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InviteStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("InviteToken")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OptOutToken")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("OptedOutAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InviteToken")
                        .IsUnique()
                        .HasFilter("\"InviteToken\" IS NOT NULL");

                    b.HasIndex("OptOutToken")
                        .IsUnique()
                        .HasFilter("\"OptOutToken\" IS NOT NULL");

                    b.HasIndex("PoolId", "PhoneNumber")
                        .IsUnique();

                    b.ToTable("Casuals");
                });

            modelBuilder.Entity("ShiftDrop.Domain.CasualAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CasualId")
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("FromTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("ToTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CasualId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("CasualAvailability");
                });

            modelBuilder.Entity("ShiftDrop.Domain.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextRetryAt")
                        .HasFilter("\"Status\" = 'Pending'");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("ShiftDrop.Domain.Pool", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManagerAuth0Id")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerAuth0Id");

                    b.ToTable("Pools");
                });

            modelBuilder.Entity("ShiftDrop.Domain.PoolAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Auth0Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("InviteExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InviteToken")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Auth0Id")
                        .HasFilter("\"Auth0Id\" IS NOT NULL");

                    b.HasIndex("InviteToken")
                        .IsUnique()
                        .HasFilter("\"InviteToken\" IS NOT NULL");

                    b.HasIndex("PoolId", "PhoneNumber")
                        .IsUnique();

                    b.ToTable("PoolAdmins");
                });

            modelBuilder.Entity("ShiftDrop.Domain.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("CasualId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("CasualId", "Endpoint")
                        .IsUnique();

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("ShiftDrop.Domain.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid");

                    b.Property<int>("SpotsNeeded")
                        .HasColumnType("integer");

                    b.Property<int>("SpotsRemaining")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PoolId", "Status", "StartsAt");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("ShiftDrop.Domain.ShiftClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CasualId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CasualId");

                    b.HasIndex("ShiftId", "CasualId", "Status");

                    b.ToTable("ShiftClaims");
                });

            modelBuilder.Entity("ShiftDrop.Domain.ShiftNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CasualId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClaimToken")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CasualId");

                    b.HasIndex("ClaimToken")
                        .IsUnique();

                    b.HasIndex("ShiftId", "TokenStatus");

                    b.ToTable("ShiftNotifications");
                });

            modelBuilder.Entity("ShiftDrop.Domain.Casual", b =>
                {
                    b.HasOne("ShiftDrop.Domain.Pool", "Pool")
                        .WithMany("Casuals")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pool");
                });

            modelBuilder.Entity("ShiftDrop.Domain.CasualAvailability", b =>
                {
                    b.HasOne("ShiftDrop.Domain.Casual", "Casual")
                        .WithMany("Availability")
                        .HasForeignKey("CasualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Casual");
                });

            modelBuilder.Entity("ShiftDrop.Domain.PoolAdmin", b =>
                {
                    b.HasOne("ShiftDrop.Domain.Pool", "Pool")
                        .WithMany("Admins")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pool");
                });

            modelBuilder.Entity("ShiftDrop.Domain.PushSubscription", b =>
                {
                    b.HasOne("ShiftDrop.Domain.Casual", "Casual")
                        .WithMany()
                        .HasForeignKey("CasualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Casual");
                });

            modelBuilder.Entity("ShiftDrop.Domain.Shift", b =>
                {
                    b.HasOne("ShiftDrop.Domain.Pool", "Pool")
                        .WithMany("Shifts")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pool");
                });

            modelBuilder.Entity("ShiftDrop.Domain.ShiftClaim", b =>
                {
                    b.HasOne("ShiftDrop.Domain.Casual", "Casual")
                        .WithMany("Claims")
                        .HasForeignKey("CasualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftDrop.Domain.Shift", "Shift")
                        .WithMany("Claims")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Casual");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ShiftDrop.Domain.ShiftNotification", b =>
                {
                    b.HasOne("ShiftDrop.Domain.Casual", "Casual")
                        .WithMany()
                        .HasForeignKey("CasualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftDrop.Domain.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Casual");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ShiftDrop.Domain.Casual", b =>
                {
                    b.Navigation("Availability");

                    b.Navigation("Claims");
                });

            modelBuilder.Entity("ShiftDrop.Domain.Pool", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Casuals");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("ShiftDrop.Domain.Shift", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
